<?php
########################################################################
#
# Theme : theme_bootstrap_numo
# Created : 2015-09-19 - 14:23:29
#
# Auto generated by Fluid-Template-Manager
#
# www.fluid-template-manager.de
#
########################################################################
$EM_CONF[$_EXTKEY] = array(
	'title'            => 'Numo Bootstrap Theme',
	'description'      => 'TYPO3 compatible adaption of the \"Numo - Flat Portfolio for Creatives Theme\"',
	'category'         => 'templates',
	'shy'              => 0,
	'version'          => '0.1.0',
	'dependencies'     => '',
	'conflicts'        => '',
	'priority'         => 'bottom',
	'loadOrder'        => '',
	'module'           => '',
	'state'            => 'beta',
	'uploadfolder'     => 0,
	'createDirs'       => '',
	'modify_tables'    => '',
	'clearcacheonload' => 0,
	'lockType'         => '',
	'author'           => 'Carla Froitzheim',
	'author_email'     => 'cf@computer-foto.de',
	'author_company'   => '',
	'CGLcompliance'      => '',
	'CGLcompliance_note' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
			'themes' => '1.0.1-2.99.99',
			'theme_bootstrap' => '1.0.0-9.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
	'_md5_values_when_last_written' => ''
);
?>